NAME: DeepFashion_s1

SAVE_DIR: runs
DATA:
  NUM_TRIPLETS: 100000
MODEL:
  TRANSFORMER:
    ENABLE: False
  SINGLE:
    ENABLE: True

SOLVER:
  DECAY_RATE: 0.9
  STEP_SIZE: 3
  EPOCHS: 50
  BASE_LR: 5e-5
  REGION_WEIGHT: 1.

INPUT:
  THRESHOLD: 0.1